AllCops:
  DisplayCopNames: true
Metrics/AbcSize:
  Max: 100
Metrics/ClassLength:
  Max: 125
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/MethodLength:
  Exclude:
    - '**/*.rb'
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 30
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 25
Style/Documentation:
  Enabled: false
Style/SignalException:
  Enabled: false
Layout/SpaceInsideBrackets:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
 
